catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade
catalogs:
  cli:
    '@antfu/eslint-config': ^6.7.3
    '@antfu/ni': ^28.0.0
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    publint: ^0.3.16
    simple-git-hooks: ^2.13.1
    typescript: ^5.9.3
  dev:
    '@tailwindcss/vite': ^4.1.18
    '@vitejs/plugin-vue': ^6.0.3
    '@wxt-dev/auto-icons': ^1.1.0
    '@wxt-dev/module-vue': ^1.0.3
    tailwindcss: ^4.1.18
    tw-animate-css: ^1.4.0
    vite: ^7.3.0
    vue-tsc: ^3.2.1
    wxt: ^0.20.13
  frontend:
    '@vueuse/core': ^14.1.0
    cborg: ^4.1.9
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-vue-next: ^0.562.0
    pako: ^2.1.0
    reka-ui: ^2.7.0
    tailwind-merge: ^3.4.0
    vue: ^3.5.26
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.16
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.3
    '@types/pako': ^2.0.4
    multiformats: ^13.4.2
onlyBuiltDependencies:
  - esbuild
  - spawn-sync
  - simple-git-hooks
