name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Setup JS
        uses: cwaring/ucan-devtools/.github/actions/setup-js@main
        with:
          fetch-depth: 0

      - name: Build extensions
        run: |
          pnpm "/^zip:?/"

      - name: Generate GitHub Release with Changelog
        run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets to release
        run: |
          for zip in ./.output/*-chrome.zip ./.output/*-firefox.zip; do
            gh release upload ${{ github.ref_name }} "$zip"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
